server:
  port: 8080
  compression:
      enabled: true
      mime-types: application/javascript,application/xml,text/html,text/xml,text/plain
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foo?useSSL=false&characterEncoding=utf-8
    username: foo
    password: foo
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/home/admin/fileSavePath/